Try to use terraform instead of terragrunt for formatting #patch

diff --git a/show-terraform-plan-on-pr/action.yml b/show-terraform-plan-on-pr/action.yml
--- a/show-terraform-plan-on-pr/action.yml
+++ b/show-terraform-plan-on-pr/action.yml
@@ -117,7 +117,7 @@ runs:
       working-directory: ${{ inputs.terraform_dir }}
       id: fmt
       shell: bash
-      run: terragrunt fmt -check -diff -recursive && echo "FMT_OUTCOME=success" >> $GITHUB_ENV || echo "FMT_OUTCOME=failure" >> $GITHUB_ENV
+      run: terraform fmt -check -diff -recursive && echo "FMT_OUTCOME=success" >> $GITHUB_ENV || echo "FMT_OUTCOME=failure" >> $GITHUB_ENV
 
     - name: Terraform plan
       working-directory: ${{ inputs.terraform_dir }}
