Check inputs and pass app_root and environment to WIF setup #patch

diff --git a/setup-gcloud-with-workload-identity/action.yml b/setup-gcloud-with-workload-identity/action.yml
--- a/setup-gcloud-with-workload-identity/action.yml
+++ b/setup-gcloud-with-workload-identity/action.yml
@@ -39,6 +39,15 @@ runs:
           exit 1
         fi
 
+    - name: Check inputs
+      working-directory: .
+      shell: bash
+      run: |
+        if [ -z "${{ inputs.project_id }}" ] && [ -z "${{ inputs.project_number }}" ] || [ -z "${{ inputs.environment }}" ] && [ -z "${{ inputs.app_root }}" ]; then
+          echo "ERROR: Either project_id and project_number must be set, or environment and app_root must be set"
+          exit 1
+        fi
+
     - name: Read project config
       id: read_project_config
       if: ${{ !inputs.project_id }}
